[phases.setup]
nixPkgs = ["python312", "ffmpeg"]

[phases.install]
cmd = ["python3 -m venv /opt/venv",
          ". /opt/venv/bin/activate",
          "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd =  ". /opt/venv/bin/activate && python3 bot.py"